name: CI-CD Demo

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: 拉代码
        uses: actions/checkout@v4

      - name: 设置 Docker
        uses: docker/setup-buildx-action@v3

      - name: 构建镜像
        run: docker build -t ci-demo .

      - name: 运行容器
        run: docker run ci-demo